version: "3.9"

services:

  frontend:
    build: ./frontend
    container_name: be-beetly-frontend
    command: npm run start
    ports:
      - "3000:3000"
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend/src:/usr/src/app/src


  api:
    build: ./api
    container_name: be-beetly-api
    command: npm run start
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - HOST=http://be-beetly.com
      - MONGO_URL=mongodb://api_db:27017/api
    depends_on:
      - api_db

  api_db:
    image: mongo:latest
    container_name: be-beetly-api-db
    volumes:
      - mongodb_api:/data/db

  nginx:
    image: nginx:stable-alpine
    container_name: be-beetly-docker-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend

volumes:
    mongodb_api:





